name: Build My Cudy TR3000

on:
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL: https://github.com
  REPO_BRANCH: openwrt-24.10
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: seed.config

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: 1. 检出当前仓库配置
      uses: actions/checkout@v5

    - name: 2. 初始化 Ubuntu 编译环境
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/share/powershell /usr/share/swift /local/lib/node_modules /usr/lib/google-cloud-sdk
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils qemu-utils rsync scons squashfs-tools subversion swig texinfo u-boot-tools upx-ucl unzip vim wget xmlto xz-utils zlib1g-dev zstd
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: 3. 克隆 ImmortalWrt 官方源码
      run: |
        df -h
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf "$GITHUB_WORKSPACE/openwrt" "$GITHUB_WORKSPACE/firmware"

    - name: 4. 载入自定义 Feeds (注入 Passwall 2 源)
      run: |
        [ -e $FEEDS_CONF ] && cp $FEEDS_CONF openwrt/feeds.conf.default

    - name: 5. 更新并安装扩展软件源
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: 6. 载入自定义编译配置 (seed.config)
      run: |
        [ -e $CONFIG_FILE ] && cp $CONFIG_FILE openwrt/.config
        cd openwrt
        make defconfig

    - name: 7. 下载所需的依赖包 (Download DL)
      id: package
      run: |
        cd openwrt
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: 8. 开始编译专属固件
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT

    - name: 9. 整理固件产出物
      id: organize
      if: steps.compile.outputs.status == 'success'
      run: |
        cd openwrt/bin/targets/mediatek/filogic
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: 10. 上传编译好的固件
      uses: actions/upload-artifact@v4
      if: steps.organize.outputs.status == 'success'
      with:
        name: ImmortalWrt_Cudy_TR3000_Passwall2
        path: ${{ env.FIRMWARE }}/*sysupgrade*
